### ISSUE TITLE
Chore: 폴더 구조 추가

### ISSUE THREAD

**Issue by jongsujin** [Yanol-Market/FE_Yanol-Market#1]
## Description
효주님이 올려주신 폴더 구조 바탕으로 목서버와 기타 패키지 등 추가 예정입니다

## Todo

- [ ] pages , apis , component , styles , recoil , utils 추가
- [ ] msw 서버 셋팅
- [ ] recoil , react-query 설치

## ETC
이슈 템플릿을 제가 못만들어서 일단 복붙으로 했습니다!
